
POST http://localhost:5183/User
Content-Type: application/json

{
    "Id": "1",
    "EmailAddress": "carl@mail.se",
    "PassWord": "test123!"
}

###

GET http://localhost:5183/User

###

POST https://localhost:7220/Highscore
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY2FybGFmYWxrIiwianRpIjoiNmNmNjQ5OWItMjJmMS00MWE1LWE3MjQtODY1YTA0MDkxOTFhIiwiZXhwIjoxNjY5NDgxMjQ1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.xFf4cpuADBVUnK2dLvKTE1OYL9mRD_ujmLb7aJn4nKo

{
    "Id": "2",
    "UserId": "1",
    "WPM": 50,
    "Accuracy": 0.7
}

###

GET https://localhost:7220/Highscore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY2FybGFmYWxrIiwianRpIjoiNmNmNjQ5OWItMjJmMS00MWE1LWE3MjQtODY1YTA0MDkxOTFhIiwiZXhwIjoxNjY5NDgxMjQ1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.xFf4cpuADBVUnK2dLvKTE1OYL9mRD_ujmLb7aJn4nKo


###

POST https://localhost:7220/Authenticate/register
Content-Type: application/json

{
    "Username" : "carlafalk",
    "Email" : "carl@mail.com",
    "Password" : "test123!T"
}

###

POST https://localhost:7220/Authenticate/Login
Content-Type: application/json

{
    "Username" : "carlafalk",
    "Password" : "test123!T"
}